### PR TITLE
Adding scripts to installing Edge Preview and Validating Edge installed.

### PR DESCRIPTION
**Pull request by stanleyhon**
Add script to install Edge Preview and validate it is installed correctly.

### CODE REVIEW

**Comment by stanleyhon** [comment]
@vtbassmatt @joebourneMS @PBoraMSFT

**Comment by vtbassmatt** [comment]
I think you've got to put it in the image JSON as well. For example: https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/vs2019-Server2019-Azure.json

**Comment by stanleyhon** [comment]
@vtbassmatt I've added it to the JSONs.

Let me know if there's anything else that needs to change.

**Comment by vtbassmatt** [comment]
Fixes #848

**Comment by kaylangan** [comment]
@PBoraMSFT can you or someone on your team take a look as owners of the "Testing" ecosystem? Since this is a preview version, I think you'll want to think about how you'll monitor for new versions of the preview and updating to the GA version when it goes live.

**Comment by stanleyhon** [comment]
@kaylangan any updates here?

**Comment by stanleyhon** [comment]
Not stale, still looking to check this in.

**Pull request closed without merging**
