### PR TITLE
Pin cloud foundry cli version 6.46.1 because the latest version windows download is broken

### PR DESCRIPTION
**Pull request by yl2558**
Related issues 
https://github.com/cloudfoundry/cli/issues/1819
https://github.com/cloudfoundry/cli/issues/1820

### CODE REVIEW

**Comment by abbyachau** [comment]
Hi @yl2558 cf CLI team here. The engs are still working on a release for Windows support. In the meantime, we plan on adding a redirect for Windows to point to 6.46.1, which is the latest known working version. Here is the story to track: https://www.pivotaltracker.com/story/show/169295723 for the redirect. Let us know if you have any feedback. Thanks. Sorry again about the disruption.

**Comment by abbyachau** [comment]
A quick update: we are still working on Windows Support. In the meantime, the cf CLI eng team applied a temporary fix for the Windows issue: links for the latest Windows version temporarily redirects to use cf CLI 6.46.1 which is the last known working version. It looks like this does not affect you since you've pinned already - but wanted to give you a heads up.

The Linux and OSX installers/binaries are still pointing at cf CLI 6.47.1, which fixes the aforementioned regression for login. Once we have the new Windows cert working, we will release Windows support which will be on par with cf CLI 6.47.1. 

Please reach out if you have any questions or concerns, thanks.

Abby

**Comment by kaylangan** [comment]
I believe this should fix #1333

**Comment by abbyachau** [comment]
Hey @yl2558  we released [cf CLI 6.47.1](https://github.com/cloudfoundry/cli/releases/tag/v6.47.1) yesterday with Windows support. Sorry again about the interruption. Please let us know if you have any feedback, thanks.

**Comment by alepauly** [comment]
Fixed on the CF side so this change is no longer required.

**Pull request closed without merging**
