### PR TITLE
Add Dotfuscator to Visual Studio 2019

### PR DESCRIPTION
**Pull request by gmarino-preemptive**
This Pull request will add Dotfuscator Community as a component installed in Visual Studio 2019 on `windows-2019` agents. Both of the other agents (`vs2015-win2012r2` and `vs2017-win2016`) come with Dotfuscator already installed, but in the process of updating the Dotfuscator Community build task we noticed it was not installed on the 2019 agents.

We would like to add Dotfuscator to the 2019 image so that users can protect their application in the latest version of Visual Studio using the Dotfuscator Community build task.

The Dotfuscator Build Task can be found on the Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=PreEmptiveSolutions.dotfuscator-ce-vsts

### CODE REVIEW

**Comment by kaylangan** [comment]
@gmarino-preemptive thanks for the contribution. This looks good to me. Before I merge, can you revert the changes to the README? We generate and update the README when we cut a new release and the tool becomes available.

**Comment by gmarino-preemptive** [comment]
@kaylangan I just reverted the README to the version on `master`, let me know if there's anything else I need to take care of.

**Comment by kaylangan** [comment]
Thanks for the contribution!

**Comment by gmarino-preemptive** [comment]
Thank you!

**Pull request merged**
