### PR TITLE
Fix for 1276. 

### PR DESCRIPTION
**Pull request by azureDaveOps**
Writing over Microsoft.NET.Sdk.ImportPublishProfile.targets until 3.1 SDK brings in the fix.

### CODE REVIEW

**Comment by kaylangan** [comment]
Kicked off builds for VS2017 and VS2019:
- https://dev.azure.com/mseng/AzureDevOps/_build/results?buildId=10733502&view=results
- https://dev.azure.com/mseng/AzureDevOps/_build/results?buildId=10733503&view=results

**Comment by kaylangan** [comment]
Builds failed with what looks like an intermittent error. Re-running...

**Comment by alepauly** [comment]
this should be good to merge right @azureDaveOps, @kaylangan? or do we need to wait on anything?

**Comment by azureDaveOps** [comment]
Thanks Alejandro! Completed!

**Pull request merged**
