### PR TITLE
Add PCL component to VS2019 image

### PR DESCRIPTION
**Pull request by JamesNK**
Add Microsoft.VisualStudio.Component.PortableLibrary to VS2019

Fixes https://github.com/microsoft/azure-pipelines-image-generation/issues/974

### CODE REVIEW

**Comment by kaylangan** [comment]
Should we consider adding this component to the VS2017 image as well?

**Comment by Daniel-Svensson** [comment]
@kaylangan the corresponding component is already installed for the hosted vs2017 image

**Comment by kaylangan** [comment]
Thanks for the contribution, @JamesNK! This will be available in the M155 deployment which will start sometime the week of 7/15.

**Comment by JamesNK** [comment]
@kaylangan When will this be available? The M155 release is currently listed as prerelease: https://github.com/microsoft/azure-pipelines-image-generation/releases/tag/VS2019%2F155.1

**Comment by kaylangan** [comment]
We started the deployment at the end of last week and anticipate to be completely rolled out by mid/end of this week.

**Pull request merged**
