### PR TITLE
Change default VM size to a sku with nested virtualization

### PR DESCRIPTION
**Pull request by syedhassaanahmed**
Since both VM images support Docker, we should choose a default Azure VM sku which has [nested virtualization support](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/acu). Otherwise running docker tasks on these agents fails with error;
```
No hypervisor is present on this system
```

### CODE REVIEW

**Comment by nelsonjchen** [comment]
What are the chances of this making it in? If not existing VM images, can this be done for `1809`-based OSes?

**Comment by nelsonjchen** [comment]
The use case I'm trying to push forth in "https://github.com/rust-lang/docker-rust/issues/30" is building and testing images for all the differing in-between versions of Windows and apparently working around not facing some bugs in some older Windows's process isolation with VS Build Tools. For example, no online CI providers offer `1709` and we're having trouble installing VS Build Tools in an LTSC 2016 image without some process-isolation only call or filter driver stuff erroring out (All builds are on a building and test-only basis, but especially MSVC-based ones).

**Comment by nelsonjchen** [comment]
Oof, https://github.com/Microsoft/azure-pipelines-image-generation/issues/182 , now I'm not so sure anymore. Here's to hoping the Windows Server 2019 image runs on a nested virtualization capable host.

**Comment by syedhassaanahmed** [comment]
@lokesh755 @DavidStaheli @chrisrpatterson Can you please take a look at this PR? Thanks

**Pull request closed without merging**
