### PR TITLE
Spec arch to node.js in Vs2017-Server2016 image

### PR DESCRIPTION
**Pull request by pablonete**
Addresses #611 
Added node `arch`.
Updated node version to current one, see today's build: https://dev.azure.com/pablo-nunez/Runner/_build/results?buildId=304

### CODE REVIEW

**Comment by pablonete** [comment]
@DavidStaheli @willsmythe May you guys review/merge this update? Thanks!

**Comment by DavidStaheli** [comment]
@pablonete thank you for this clarification to the readme!  @alepauly @shadyysf @pasangh this change is accurate based on [Pablo's build](https://dev.azure.com/pablo-nunez/Runner/_build/results?buildId=304), but do you now have a special process for updating the readme, or can we merge this now?

**Comment by alepauly** [comment]
> do you now have a special process for updating the readme, or can we merge this now?
We shouldn't update this by hand unless completely necessary. The image generation process generates this output automatically but we have to copy it into the proper readme file when it's done so either 1) the image includes the older version and we shouldn't update the readme, or more likely 2) the readme didn't get updated. @shadyysf generated the last one I think, do you still have the corresponding InstalledSoftware that gets generated?

**Comment by bryanmacfarlane** [comment]
We use to merge it when the image was released.  (in all rings)

**Comment by bryanmacfarlane** [comment]
Agreed on manual edits being an anti-pattern.  We should update the gen code.

**Comment by pablonete** [comment]
Thank you all. So I've updated the script that generates the Readme, so the new Architecture is also auto-generated in the future. I've tested it locally. Can you guys take another look here @bryanmacfarlane @alepauly @DavidStaheli?

**Pull request merged**
