### PR TITLE
Add Validate-SQLPowerShellTools to VS2019 on WS2019 template

### LINKED ISSUE #983: Validate-SQLPowerShellTools missing from VS2019 on WS2019 template
**Describe the bug**
Validate-SQLPowerShellTools missing from VS2019 on WS2019 template. I'm submitting a PR to add it in case folks want it.

**Expected behavior**
Validate-SQLPowerShellTools is there in the VS2017 on WS2016 template so I am unsure why it's missing in the VS2019 on WS2019 template.

**Actual behavior**
Validate-SQLPowerShellTools missing from VS2019 on WS2019 template

**Image impacted**
windows

### PR DESCRIPTION
**Pull request by ryanspletzer**
Fixes #983

### CODE REVIEW

**Comment by vtbassmatt** [comment]
I think the database ecosystem team should approve this, it's about SQL PowerShell tools (not PowerShell itself).

**Comment by kmkumaran** [comment]
adding @Ajay-MS who owns the SQL tools to review.

**Comment by ryanspletzer** [comment]
Hey just saw this was closed. Shouldn't this be merged in want this incorporated? Right now Install-SQLPowerShellTools is in the template but not the associated validate script.

**Comment by RoopeshNair** [comment]
@Ajay-MS - re-opening the PR

**Comment by alepauly** [comment]
@ryanspletzer - thanks for the PR and sorry it's taken so long to merge. I'll move it over to actions/virtual-environments from where we are working now. I'll add you there as a reviewer once it's up.

**Pull request closed without merging**
