### PR TITLE
Android sdk-tools update and Linux dynamic version output

### PR DESCRIPTION
**Pull request by DavidStaheli**
This adds to the Android SDK licenses that are installed on Windows.
The only tool version updated by this PR is the **SDK-Tools** on Windows:
- sdk-tools-windows-**3859397**.zip

is updated to:
- sdk-tools-windows-**4333796**.zip (latest)

This PR was prompted by #382.

### CODE REVIEW

**Comment by mossey** [comment]
Having an issue with building for android 28.0.3. I hope merging this PR helps

**Comment by DavidStaheli** [comment]
Hi @mossey.  It may be that 28.0.3 hasn't made it to production yet for the Hosted VS2017 (Windows) agent.  You might want to try the Hosted macOS agent, or if you have a specific error we can try to help.

**Comment by mossey** [comment]
> Hi @mossey. It may be that 28.0.3 hasn't made it to production yet for the Hosted VS2017 (Windows) agent. You might want to try the Hosted macOS agent, or if you have a specific error we can try to help.

It works on the macOS agent. Thanks !

**Comment by DavidStaheli** [comment]
@mossey, here is a workaround for the 28.0.3 issue until this PR gets deployed to production.

1. Add a [PowerShell](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=vsts) step to the very beginning of your pipeline. Set the inline PowerShell script to be the following, which updates the Android licenses on the VS2017 virtual machine:

```powershell
Get-ChildItem -path 'C:\Program Files (x86)\Android\android-sdk\licenses' | Remove-Item -Recurse -Confirm:$false -Force
dir 'C:\Program Files (x86)\Android\android-sdk\licenses'
$base64Content = "UEsDBBQAAAAAAKJeN06amkPzKgAAACoAAAAhAAAAbGljZW5zZXMvYW5kcm9pZC1nb29nbGV0di1saWNlbnNlDQpmYzk0NmU4ZjIzMWYzZTMxNTliZjBiN2M2NTVjOTI0Y2IyZTM4MzMwUEsDBBQAAAAIAKBrN05E+YSqQwAAAFQAAAAcAAAAbGljZW5zZXMvYW5kcm9pZC1zZGstbGljZW5zZQXByREAIQgEwP9WmYsjhxgOKJN/CNs9vmdOQ2zdRw2dxQnWjqQ/3oIgXQM9vqUiwkiX8ljWea4ZlCF3xTo1pz6w+wdQSwMEFAAAAAAAxV43TpECY7AqAAAAKgAAACQAAABsaWNlbnNlcy9hbmRyb2lkLXNkay1wcmV2aWV3LWxpY2Vuc2UNCjUwNDY2N2Y0YzBkZTdhZjFhMDZkZTlmNGIxNzI3Yjg0MzUxZjI5MTBQSwMEFAAAAAAAzF43TpOr0CgqAAAAKgAAABsAAABsaWNlbnNlcy9nb29nbGUtZ2RrLWxpY2Vuc2UNCjMzYjZhMmI2NDYwN2YxMWI3NTlmMzIwZWY5ZGZmNGFlNWM0N2Q5N2FQSwMEFAAAAAAAz143TqxN4xEqAAAAKgAAACQAAABsaWNlbnNlcy9pbnRlbC1hbmRyb2lkLWV4dHJhLWxpY2Vuc2UNCmQ5NzVmNzUxNjk4YTc3YjY2MmYxMjU0ZGRiZWVkMzkwMWU5NzZmNWFQSwMEFAAAAAAA0l43Tu2ee/8qAAAAKgAAACYAAABsaWNlbnNlcy9taXBzLWFuZHJvaWQtc3lzaW1hZ2UtbGljZW5zZQ0KNjNkNzAzZjU2OTJmZDg5MWQ1YWNhY2ZiZDhlMDlmNDBmYzk3NjEwNVBLAQIUABQAAAAAAKJeN06amkPzKgAAACoAAAAhAAAAAAAAAAEAIAAAAAAAAABsaWNlbnNlcy9hbmRyb2lkLWdvb2dsZXR2LWxpY2Vuc2VQSwECFAAUAAAACACgazdORPmEqkMAAABUAAAAHAAAAAAAAAABACAAAABpAAAAbGljZW5zZXMvYW5kcm9pZC1zZGstbGljZW5zZVBLAQIUABQAAAAAAMVeN06RAmOwKgAAACoAAAAkAAAAAAAAAAEAIAAAAOYAAABsaWNlbnNlcy9hbmRyb2lkLXNkay1wcmV2aWV3LWxpY2Vuc2VQSwECFAAUAAAAAADMXjdOk6vQKCoAAAAqAAAAGwAAAAAAAAABACAAAABSAQAAbGljZW5zZXMvZ29vZ2xlLWdkay1saWNlbnNlUEsBAhQAFAAAAAAAz143TqxN4xEqAAAAKgAAACQAAAAAAAAAAQAgAAAAtQEAAGxpY2Vuc2VzL2ludGVsLWFuZHJvaWQtZXh0cmEtbGljZW5zZVBLAQIUABQAAAAAANJeN07tnnv/KgAAACoAAAAmAAAAAAAAAAEAIAAAACECAABsaWNlbnNlcy9taXBzLWFuZHJvaWQtc3lzaW1hZ2UtbGljZW5zZVBLBQYAAAAABgAGANoBAACPAgAAAAA="
$content = [System.Convert]::FromBase64String($base64Content)
Set-Content -Path .\android-sdk-licenses.zip -Value $content -Encoding Byte
Expand-Archive -Path .\android-sdk-licenses.zip -DestinationPath 'C:\Program Files (x86)\Android\android-sdk' -Force
dir 'C:\Program Files (x86)\Android\android-sdk\licenses'
```

2. Verify that after the PowerShell step runs at the start of your build, the rest of the build succeeds again.

**Pull request merged**
